[project]
name = "gnomecast"
version = "1.9.11"
requires-python = ">=3.10"
dependencies = [
    "bottle~=0.13.3",
    "html5lib~=1.1",
    "paste~=3.10.1",
    "pycaption~=2.2.16",
    "pychromecast~=13.1.0",
    "pygobject~=3.52.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
